// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: VectorialClockService.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_APPLICATION MessageType = 0
	MessageType_ACK         MessageType = 1
	MessageType_SYSTEM      MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "APPLICATION",
		1: "ACK",
		2: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"APPLICATION": 0,
		"ACK":         1,
		"SYSTEM":      2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_VectorialClockService_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_VectorialClockService_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_VectorialClockService_proto_rawDescGZIP(), []int{0}
}

type MessageVC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=MessageType" json:"type,omitempty"`
	Clock []uint64    `protobuf:"varint,2,rep,packed,name=clock,proto3" json:"clock,omitempty"`
	Src   string      `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Id    string      `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Data  string      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MessageVC) Reset() {
	*x = MessageVC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VectorialClockService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageVC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageVC) ProtoMessage() {}

func (x *MessageVC) ProtoReflect() protoreflect.Message {
	mi := &file_VectorialClockService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageVC.ProtoReflect.Descriptor instead.
func (*MessageVC) Descriptor() ([]byte, []int) {
	return file_VectorialClockService_proto_rawDescGZIP(), []int{0}
}

func (x *MessageVC) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_APPLICATION
}

func (x *MessageVC) GetClock() []uint64 {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *MessageVC) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MessageVC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageVC) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type EnqueueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnqueueReply) Reset() {
	*x = EnqueueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VectorialClockService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnqueueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueReply) ProtoMessage() {}

func (x *EnqueueReply) ProtoReflect() protoreflect.Message {
	mi := &file_VectorialClockService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueReply.ProtoReflect.Descriptor instead.
func (*EnqueueReply) Descriptor() ([]byte, []int) {
	return file_VectorialClockService_proto_rawDescGZIP(), []int{1}
}

var File_VectorialClockService_proto protoreflect.FileDescriptor

var file_VectorialClockService_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x43, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a,
	0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x56, 0x43, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x72, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6e, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2a, 0x33, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x50, 0x50, 0x4c, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x02, 0x32, 0x36, 0x0a,
	0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x51, 0x75, 0x65, 0x75, 0x65, 0x56, 0x43, 0x12,
	0x24, 0x0a, 0x07, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x0a, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x56, 0x43, 0x1a, 0x0d, 0x2e, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x16, 0x5a, 0x14, 0x73, 0x64, 0x63, 0x63, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_VectorialClockService_proto_rawDescOnce sync.Once
	file_VectorialClockService_proto_rawDescData = file_VectorialClockService_proto_rawDesc
)

func file_VectorialClockService_proto_rawDescGZIP() []byte {
	file_VectorialClockService_proto_rawDescOnce.Do(func() {
		file_VectorialClockService_proto_rawDescData = protoimpl.X.CompressGZIP(file_VectorialClockService_proto_rawDescData)
	})
	return file_VectorialClockService_proto_rawDescData
}

var file_VectorialClockService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_VectorialClockService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_VectorialClockService_proto_goTypes = []interface{}{
	(MessageType)(0),     // 0: MessageType
	(*MessageVC)(nil),    // 1: MessageVC
	(*EnqueueReply)(nil), // 2: EnqueueReply
}
var file_VectorialClockService_proto_depIdxs = []int32{
	0, // 0: MessageVC.type:type_name -> MessageType
	1, // 1: MessageQueueVC.Enqueue:input_type -> MessageVC
	2, // 2: MessageQueueVC.Enqueue:output_type -> EnqueueReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_VectorialClockService_proto_init() }
func file_VectorialClockService_proto_init() {
	if File_VectorialClockService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_VectorialClockService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageVC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VectorialClockService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnqueueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_VectorialClockService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_VectorialClockService_proto_goTypes,
		DependencyIndexes: file_VectorialClockService_proto_depIdxs,
		EnumInfos:         file_VectorialClockService_proto_enumTypes,
		MessageInfos:      file_VectorialClockService_proto_msgTypes,
	}.Build()
	File_VectorialClockService_proto = out.File
	file_VectorialClockService_proto_rawDesc = nil
	file_VectorialClockService_proto_goTypes = nil
	file_VectorialClockService_proto_depIdxs = nil
}
