// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageQueueLCClient is the client API for MessageQueueLC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageQueueLCClient interface {
	Enqueue(ctx context.Context, in *MessageLC, opts ...grpc.CallOption) (*EnqueueReply, error)
}

type messageQueueLCClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueueLCClient(cc grpc.ClientConnInterface) MessageQueueLCClient {
	return &messageQueueLCClient{cc}
}

func (c *messageQueueLCClient) Enqueue(ctx context.Context, in *MessageLC, opts ...grpc.CallOption) (*EnqueueReply, error) {
	out := new(EnqueueReply)
	err := c.cc.Invoke(ctx, "/MessageQueueLC/Enqueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageQueueLCServer is the server API for MessageQueueLC service.
// All implementations must embed UnimplementedMessageQueueLCServer
// for forward compatibility
type MessageQueueLCServer interface {
	Enqueue(context.Context, *MessageLC) (*EnqueueReply, error)
	mustEmbedUnimplementedMessageQueueLCServer()
}

// UnimplementedMessageQueueLCServer must be embedded to have forward compatible implementations.
type UnimplementedMessageQueueLCServer struct {
}

func (UnimplementedMessageQueueLCServer) Enqueue(context.Context, *MessageLC) (*EnqueueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedMessageQueueLCServer) mustEmbedUnimplementedMessageQueueLCServer() {}

// UnsafeMessageQueueLCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueueLCServer will
// result in compilation errors.
type UnsafeMessageQueueLCServer interface {
	mustEmbedUnimplementedMessageQueueLCServer()
}

func RegisterMessageQueueLCServer(s grpc.ServiceRegistrar, srv MessageQueueLCServer) {
	s.RegisterService(&MessageQueueLC_ServiceDesc, srv)
}

func _MessageQueueLC_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageLC)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageQueueLCServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MessageQueueLC/Enqueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageQueueLCServer).Enqueue(ctx, req.(*MessageLC))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageQueueLC_ServiceDesc is the grpc.ServiceDesc for MessageQueueLC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQueueLC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MessageQueueLC",
	HandlerType: (*MessageQueueLCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _MessageQueueLC_Enqueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LamportClockService.proto",
}
